services:
  elasticsearch:
    container_name: es-container
    environment:
    - xpack.security.enabled=false
    - discovery.type=single-node
    image: "docker.elastic.co/elasticsearch/elasticsearch:8.1.1"
    networks:
    - es-net
    ports:
    - "9200:9200"
  kibana:
    depends_on:
    - elasticsearch
    environment:
    - "ELASTICSEARCH_HOSTS=http://es-container:9200"
    image: "docker.elastic.co/kibana/kibana:8.1.1"
    networks:
    - es-net
    ports:
    - "5601:5601"
version: "3.9"
volumes:
  db-data:
    name: db-data
networks:
  es-net:
    driver: bridge
